spring:
  application:
    name: redis
  server:
    port: 8080

  data:
    redis:
      repositories:
        enabled: true
      client:
        host: localhost
        port: 6379
        password: yourpassword # Uncomment and set if Redis requires authentication
        database: 0
        timeout: 2000
        client-type: lettuce
